<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class MasterBankSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $banks = [
            // ===== BANK UMUM / HIMBARA / NASIONAL =====
            [
                'kode_bank' => '008',
                'nama_bank' => 'PT Bank Mandiri (Persero) Tbk',
                'nama_bank_pendek' => 'Bank Mandiri',
                'swift_code' => 'BMRIIDJA',
                'tipe_bank' => 'BUK',
            ],
            [
                'kode_bank' => '002',
                'nama_bank' => 'PT Bank Rakyat Indonesia (Persero) Tbk',
                'nama_bank_pendek' => 'BRI',
                'swift_code' => 'BRINIDJA',
                'tipe_bank' => 'BUK',
            ],
            [
                'kode_bank' => '009',
                'nama_bank' => 'PT Bank Negara Indonesia (Persero) Tbk',
                'nama_bank_pendek' => 'BNI',
                'swift_code' => 'BNINIDJA',
                'tipe_bank' => 'BUK',
            ],
            [
                'kode_bank' => '200',
                'nama_bank' => 'PT Bank Tabungan Negara (Persero) Tbk',
                'nama_bank_pendek' => 'BTN',
                'swift_code' => 'BTANIDJA',
                'tipe_bank' => 'BUK',
            ],
            [
                'kode_bank' => '014',
                'nama_bank' => 'PT Bank Central Asia Tbk',
                'nama_bank_pendek' => 'BCA',
                'swift_code' => 'CENAIDJA',
                'tipe_bank' => 'BUK',
            ],
            [
                'kode_bank' => '022',
                'nama_bank' => 'PT Bank CIMB Niaga Tbk',
                'nama_bank_pendek' => 'CIMB Niaga',
                'swift_code' => 'BNIAIDJA',
                'tipe_bank' => 'BUK',
            ],
            [
                'kode_bank' => '011',
                'nama_bank' => 'PT Bank Danamon Indonesia Tbk',
                'nama_bank_pendek' => 'Danamon',
                'swift_code' => 'BDINIDJA',
                'tipe_bank' => 'BUK',
            ],
            [
                'kode_bank' => '013',
                'nama_bank' => 'PT Bank Permata Tbk',
                'nama_bank_pendek' => 'PermataBank',
                'swift_code' => 'BBBAIDJA',
                'tipe_bank' => 'BUK',
            ],
            [
                'kode_bank' => '019',
                'nama_bank' => 'PT Bank Pan Indonesia Tbk',
                'nama_bank_pendek' => 'Panin Bank',
                'swift_code' => 'PINBIDJA',
                'tipe_bank' => 'BUK',
            ],
            [
                'kode_bank' => '028',
                'nama_bank' => 'PT Bank OCBC NISP Tbk',
                'nama_bank_pendek' => 'OCBC',
                'swift_code' => 'NISPIDJA',
                'tipe_bank' => 'BUK',
            ],
            [
                'kode_bank' => '023',
                'nama_bank' => 'PT Bank UOB Indonesia',
                'nama_bank_pendek' => 'UOB Indonesia',
                'swift_code' => 'UOBIIDJA',
                'tipe_bank' => 'BUK',
            ],
            [
                'kode_bank' => '016',
                'nama_bank' => 'PT Bank Maybank Indonesia Tbk',
                'nama_bank_pendek' => 'Maybank Indonesia',
                'swift_code' => 'IBBKIDJA',
                'tipe_bank' => 'BUK',
            ],
            [
                'kode_bank' => '441',
                'nama_bank' => 'PT Bank KB Bukopin Tbk',
                'nama_bank_pendek' => 'KB Bukopin',
                'swift_code' => 'BBUKIDJA',
                'tipe_bank' => 'BUK',
            ],
            [
                'kode_bank' => '426',
                'nama_bank' => 'PT Bank Mega Tbk',
                'nama_bank_pendek' => 'Bank Mega',
                'swift_code' => 'MEGAIDJA',
                'tipe_bank' => 'BUK',
            ],
            [
                'kode_bank' => '153',
                'nama_bank' => 'PT Bank Sinarmas Tbk',
                'nama_bank_pendek' => 'Bank Sinarmas',
                'swift_code' => 'SBJKIDJA',
                'tipe_bank' => 'BUK',
            ],
            [
                'kode_bank' => '213',
                'nama_bank' => 'PT Bank BTPN Tbk',
                'nama_bank_pendek' => 'BTPN',
                'swift_code' => 'SUNIIDJA',
                'tipe_bank' => 'BUK',
            ],
            [
                'kode_bank' => '542',
                'nama_bank' => 'PT Bank Jago Tbk',
                'nama_bank_pendek' => 'Bank Jago',
                'swift_code' => null,
                'tipe_bank' => 'DIGITAL',
            ],
            [
                'kode_bank' => '490',
                'nama_bank' => 'PT Bank Neo Commerce Tbk',
                'nama_bank_pendek' => 'Bank Neo Commerce',
                'swift_code' => null,
                'tipe_bank' => 'DIGITAL',
            ],
            [
                'kode_bank' => '405',
                'nama_bank' => 'PT Bank Raya Indonesia Tbk',
                'nama_bank_pendek' => 'Bank Raya',
                'swift_code' => null,
                'tipe_bank' => 'DIGITAL',
            ],
            [
                'kode_bank' => '947',
                'nama_bank' => 'PT Allo Bank Indonesia Tbk',
                'nama_bank_pendek' => 'Allo Bank',
                'swift_code' => null,
                'tipe_bank' => 'DIGITAL',
            ],
            [
                'kode_bank' => '535',
                'nama_bank' => 'PT Bank Seabank Indonesia',
                'nama_bank_pendek' => 'SeaBank',
                'swift_code' => null,
                'tipe_bank' => 'DIGITAL',
            ],
            [
                'kode_bank' => '531',
                'nama_bank' => 'PT Bank Amar Indonesia Tbk',
                'nama_bank_pendek' => 'Bank Amar',
                'swift_code' => null,
                'tipe_bank' => 'DIGITAL',
            ],
            [
                'kode_bank' => '503',
                'nama_bank' => 'PT Bank Nationalnobu Tbk',
                'nama_bank_pendek' => 'Nobu Bank',
                'swift_code' => null,
                'tipe_bank' => 'BUK',
            ],
            [
                'kode_bank' => '485',
                'nama_bank' => 'PT Bank JTrust Indonesia Tbk',
                'nama_bank_pendek' => 'JTrust Bank',
                'swift_code' => null,
                'tipe_bank' => 'BUK',
            ],
            [
                'kode_bank' => '949',
                'nama_bank' => 'PT Bank MNC Internasional Tbk',
                'nama_bank_pendek' => 'MNC Bank',
                'swift_code' => null,
                'tipe_bank' => 'BUK',
            ],
            [
                'kode_bank' => '157',
                'nama_bank' => 'PT Bank Maspion Indonesia Tbk',
                'nama_bank_pendek' => 'Bank Maspion',
                'swift_code' => null,
                'tipe_bank' => 'BUK',
            ],
            [
                'kode_bank' => '097',
                'nama_bank' => 'PT Bank Mayapada Internasional Tbk',
                'nama_bank_pendek' => 'Mayapada',
                'swift_code' => null,
                'tipe_bank' => 'BUK',
            ],
            [
                'kode_bank' => '151',
                'nama_bank' => 'PT Bank Mestika Dharma Tbk',
                'nama_bank_pendek' => 'Bank Mestika',
                'swift_code' => null,
                'tipe_bank' => 'BUK',
            ],
            [
                'kode_bank' => '161',
                'nama_bank' => 'PT Bank Ganesha Tbk',
                'nama_bank_pendek' => 'Bank Ganesha',
                'swift_code' => null,
                'tipe_bank' => 'BUK',
            ],
            [
                'kode_bank' => '076',
                'nama_bank' => 'PT Bank Bumi Arta Tbk',
                'nama_bank_pendek' => 'Bank Bumi Arta',
                'swift_code' => null,
                'tipe_bank' => 'BUK',
            ],
            [
                'kode_bank' => '037',
                'nama_bank' => 'PT Bank Artha Graha Internasional Tbk',
                'nama_bank_pendek' => 'Artha Graha',
                'swift_code' => null,
                'tipe_bank' => 'BUK',
            ],
            [
                'kode_bank' => '566',
                'nama_bank' => 'PT Bank Multiarta Sentosa Tbk',
                'nama_bank_pendek' => 'Bank MAS',
                'swift_code' => null,
                'tipe_bank' => 'BUK',
            ],
            [
                'kode_bank' => '466',
                'nama_bank' => 'PT Bank Ina Perdana Tbk',
                'nama_bank_pendek' => 'Bank Ina',
                'swift_code' => null,
                'tipe_bank' => 'BUK',
            ],
            [
                'kode_bank' => '548',
                'nama_bank' => 'PT Bank Oke Indonesia Tbk',
                'nama_bank_pendek' => 'OK Bank',
                'swift_code' => null,
                'tipe_bank' => 'BUK',
            ],
            [
                'kode_bank' => '526',
                'nama_bank' => 'PT Bank Bumi Artha Tbk',
                'nama_bank_pendek' => 'Bank Bumi Arta',
                'swift_code' => null,
                'tipe_bank' => 'BUK',
            ],

            // ===== BANK ASING / CAMPURAN / INTERNASIONAL DI INDONESIA =====
            [
                'kode_bank' => '041',
                'nama_bank' => 'PT Bank HSBC Indonesia',
                'nama_bank_pendek' => 'HSBC Indonesia',
                'swift_code' => 'HSBCIDJA',
                'tipe_bank' => 'FOREIGN',
            ],
            [
                'kode_bank' => '046',
                'nama_bank' => 'PT Bank DBS Indonesia',
                'nama_bank_pendek' => 'DBS Indonesia',
                'swift_code' => 'DBSBIDJA',
                'tipe_bank' => 'FOREIGN',
            ],
            [
                'kode_bank' => '054',
                'nama_bank' => 'PT Bank Capital Indonesia Tbk',
                'nama_bank_pendek' => 'Bank Capital',
                'swift_code' => 'BCIAIDJA',
                'tipe_bank' => 'BUK',
            ],
            [
                'kode_bank' => '050',
                'nama_bank' => 'PT Bank ICBC Indonesia',
                'nama_bank_pendek' => 'ICBC Indonesia',
                'swift_code' => 'ICBKIDJA',
                'tipe_bank' => 'FOREIGN',
            ],
            [
                'kode_bank' => '059',
                'nama_bank' => 'PT Bank KEB Hana Indonesia',
                'nama_bank_pendek' => 'KEB Hana',
                'swift_code' => 'HNBNIDJA',
                'tipe_bank' => 'FOREIGN',
            ],
            [
                'kode_bank' => '9491',
                'nama_bank' => 'PT Bank CTBC Indonesia',
                'nama_bank_pendek' => 'CTBC Indonesia',
                'swift_code' => null,
                'tipe_bank' => 'FOREIGN',
            ],
            [
                'kode_bank' => '498',
                'nama_bank' => 'PT Bank SBI Indonesia',
                'nama_bank_pendek' => 'Bank SBI Indonesia',
                'swift_code' => 'SBINIDJA',
                'tipe_bank' => 'FOREIGN',
            ],
            [
                'kode_bank' => '047',
                'nama_bank' => 'PT Bank Resona Perdania',
                'nama_bank_pendek' => 'Resona Perdania',
                'swift_code' => 'BSPRIDJA',
                'tipe_bank' => 'FOREIGN',
            ],
            [
                'kode_bank' => '164',
                'nama_bank' => 'PT Bank IBK Indonesia Tbk',
                'nama_bank_pendek' => 'IBK Indonesia',
                'swift_code' => null,
                'tipe_bank' => 'FOREIGN',
            ],
            [
                'kode_bank' => '945',
                'nama_bank' => 'PT Bank China Construction Bank Indonesia Tbk',
                'nama_bank_pendek' => 'CCB Indonesia',
                'swift_code' => null,
                'tipe_bank' => 'FOREIGN',
            ],
            [
                'kode_bank' => '146',
                'nama_bank' => 'PT Bank of India Indonesia Tbk',
                'nama_bank_pendek' => 'Bank of India Indonesia',
                'swift_code' => 'BKIDIDJA',
                'tipe_bank' => 'FOREIGN',
            ],
            [
                'kode_bank' => '555',
                'nama_bank' => 'PT Bank Index Selindo',
                'nama_bank_pendek' => 'Bank Index',
                'swift_code' => null,
                'tipe_bank' => 'BUK',
            ],
            [
                'kode_bank' => '057',
                'nama_bank' => 'PT Bank BNP Paribas Indonesia',
                'nama_bank_pendek' => 'BNP Paribas Indonesia',
                'swift_code' => 'BNPAIDJA',
                'tipe_bank' => 'FOREIGN',
            ],
            [
                'kode_bank' => '068',
                'nama_bank' => 'PT Bank Woori Saudara Indonesia 1906 Tbk',
                'nama_bank_pendek' => 'Bank Woori Saudara',
                'swift_code' => null,
                'tipe_bank' => 'FOREIGN',
            ],
            [
                'kode_bank' => '061',
                'nama_bank' => 'PT Bank QNB Indonesia Tbk',
                'nama_bank_pendek' => 'QNB Indonesia',
                'swift_code' => null,
                'tipe_bank' => 'FOREIGN',
            ],

            // ===== BANK UMUM SYARIAH =====
            [
                'kode_bank' => '451',
                'nama_bank' => 'PT Bank Syariah Indonesia Tbk',
                'nama_bank_pendek' => 'BSI',
                'swift_code' => 'BSMDIDJA',
                'tipe_bank' => 'BUS',
            ],
            [
                'kode_bank' => '147',
                'nama_bank' => 'PT Bank Muamalat Indonesia Tbk',
                'nama_bank_pendek' => 'Bank Muamalat',
                'swift_code' => 'BMUIIDJA',
                'tipe_bank' => 'BUS',
            ],
            [
                'kode_bank' => '506',
                'nama_bank' => 'PT Bank Mega Syariah',
                'nama_bank_pendek' => 'Bank Mega Syariah',
                'swift_code' => 'MGSYIDJA',
                'tipe_bank' => 'BUS',
            ],
            [
                'kode_bank' => '4051',
                'nama_bank' => 'PT Bank BCA Syariah',
                'nama_bank_pendek' => 'BCA Syariah',
                'swift_code' => null,
                'tipe_bank' => 'BUS',
            ],
            [
                'kode_bank' => '547',
                'nama_bank' => 'PT Bank Panin Dubai Syariah Tbk',
                'nama_bank_pendek' => 'Panin Dubai Syariah',
                'swift_code' => null,
                'tipe_bank' => 'BUS',
            ],
            [
                'kode_bank' => '521',
                'nama_bank' => 'PT Bank Victoria Syariah',
                'nama_bank_pendek' => 'Bank Victoria Syariah',
                'swift_code' => null,
                'tipe_bank' => 'BUS',
            ],
            [
                'kode_bank' => '425',
                'nama_bank' => 'PT Bank Tabungan Pensiunan Nasional Syariah Tbk',
                'nama_bank_pendek' => 'BTPN Syariah',
                'swift_code' => null,
                'tipe_bank' => 'BUS',
            ],
            [
                'kode_bank' => '536',
                'nama_bank' => 'PT Bank Aladin Syariah Tbk',
                'nama_bank_pendek' => 'Bank Aladin Syariah',
                'swift_code' => null,
                'tipe_bank' => 'BUS',
            ],
            [
                'kode_bank' => '5211',
                'nama_bank' => 'PT Bank KB Bukopin Syariah',
                'nama_bank_pendek' => 'KB Bukopin Syariah',
                'swift_code' => null,
                'tipe_bank' => 'BUS',
            ],
            [
                'kode_bank' => '552',
                'nama_bank' => 'PT Bank Nano Syariah',
                'nama_bank_pendek' => 'Bank Nano Syariah',
                'swift_code' => null,
                'tipe_bank' => 'BUS',
            ],
            [
                'kode_bank' => '4251',
                'nama_bank' => 'PT Bank Jabar Banten Syariah',
                'nama_bank_pendek' => 'BJB Syariah',
                'swift_code' => null,
                'tipe_bank' => 'BUS',
            ],

            // ===== BPD / BPD SYARIAH =====
            [
                'kode_bank' => '110',
                'nama_bank' => 'PT Bank DKI',
                'nama_bank_pendek' => 'Bank DKI',
                'swift_code' => null,
                'tipe_bank' => 'BPD',
            ],
            [
                'kode_bank' => '111',
                'nama_bank' => 'PT Bank Pembangunan Daerah Jawa Barat dan Banten Tbk',
                'nama_bank_pendek' => 'Bank BJB',
                'swift_code' => null,
                'tipe_bank' => 'BPD',
            ],
            [
                'kode_bank' => '113',
                'nama_bank' => 'PT Bank Pembangunan Daerah Jawa Tengah',
                'nama_bank_pendek' => 'Bank Jateng',
                'swift_code' => null,
                'tipe_bank' => 'BPD',
            ],
            [
                'kode_bank' => '114',
                'nama_bank' => 'PT Bank Pembangunan Daerah Jawa Timur Tbk',
                'nama_bank_pendek' => 'Bank Jatim',
                'swift_code' => null,
                'tipe_bank' => 'BPD',
            ],
            [
                'kode_bank' => '112',
                'nama_bank' => 'PT Bank Pembangunan Daerah Daerah Istimewa Yogyakarta',
                'nama_bank_pendek' => 'Bank BPD DIY',
                'swift_code' => null,
                'tipe_bank' => 'BPD',
            ],
            [
                'kode_bank' => '115',
                'nama_bank' => 'PT Bank Pembangunan Daerah Aceh',
                'nama_bank_pendek' => 'Bank Aceh Syariah',
                'swift_code' => null,
                'tipe_bank' => 'BPD_SYARIAH',
            ],
            [
                'kode_bank' => '116',
                'nama_bank' => 'PT Bank Pembangunan Daerah Sumatera Utara',
                'nama_bank_pendek' => 'Bank Sumut',
                'swift_code' => null,
                'tipe_bank' => 'BPD',
            ],
            [
                'kode_bank' => '118',
                'nama_bank' => 'PT Bank Pembangunan Daerah Sumatera Barat',
                'nama_bank_pendek' => 'Bank Nagari',
                'swift_code' => null,
                'tipe_bank' => 'BPD',
            ],
            [
                'kode_bank' => '119',
                'nama_bank' => 'PT Bank Pembangunan Daerah Riau Kepri Syariah',
                'nama_bank_pendek' => 'BRK Syariah',
                'swift_code' => null,
                'tipe_bank' => 'BPD_SYARIAH',
            ],
            [
                'kode_bank' => '120',
                'nama_bank' => 'PT Bank Pembangunan Daerah Sumatera Selatan dan Bangka Belitung',
                'nama_bank_pendek' => 'Bank Sumsel Babel',
                'swift_code' => null,
                'tipe_bank' => 'BPD',
            ],
            [
                'kode_bank' => '121',
                'nama_bank' => 'PT Bank Pembangunan Daerah Lampung',
                'nama_bank_pendek' => 'Bank Lampung',
                'swift_code' => null,
                'tipe_bank' => 'BPD',
            ],
            [
                'kode_bank' => '122',
                'nama_bank' => 'PT Bank Pembangunan Daerah Banten Tbk',
                'nama_bank_pendek' => 'Bank Banten',
                'swift_code' => null,
                'tipe_bank' => 'BPD',
            ],
            [
                'kode_bank' => '123',
                'nama_bank' => 'PT Bank Pembangunan Daerah Bengkulu',
                'nama_bank_pendek' => 'Bank Bengkulu',
                'swift_code' => null,
                'tipe_bank' => 'BPD',
            ],
            [
                'kode_bank' => '124',
                'nama_bank' => 'PT Bank Pembangunan Daerah Jambi',
                'nama_bank_pendek' => 'Bank Jambi',
                'swift_code' => null,
                'tipe_bank' => 'BPD',
            ],
            [
                'kode_bank' => '125',
                'nama_bank' => 'PT Bank Pembangunan Daerah Kalimantan Barat',
                'nama_bank_pendek' => 'Bank Kalbar',
                'swift_code' => null,
                'tipe_bank' => 'BPD',
            ],
            [
                'kode_bank' => '126',
                'nama_bank' => 'PT Bank Pembangunan Daerah Kalimantan Selatan',
                'nama_bank_pendek' => 'Bank Kalsel',
                'swift_code' => null,
                'tipe_bank' => 'BPD',
            ],
            [
                'kode_bank' => '127',
                'nama_bank' => 'PT Bank Pembangunan Daerah Kalimantan Tengah',
                'nama_bank_pendek' => 'Bank Kalteng',
                'swift_code' => null,
                'tipe_bank' => 'BPD',
            ],
            [
                'kode_bank' => '128',
                'nama_bank' => 'PT Bank Pembangunan Daerah Kalimantan Timur dan Kalimantan Utara',
                'nama_bank_pendek' => 'Bank Kaltimtara',
                'swift_code' => null,
                'tipe_bank' => 'BPD',
            ],
            [
                'kode_bank' => '129',
                'nama_bank' => 'PT Bank Pembangunan Daerah Sulawesi Selatan dan Sulawesi Barat',
                'nama_bank_pendek' => 'Bank Sulselbar',
                'swift_code' => null,
                'tipe_bank' => 'BPD',
            ],
            [
                'kode_bank' => '130',
                'nama_bank' => 'PT Bank Pembangunan Daerah Sulawesi Utara Gorontalo',
                'nama_bank_pendek' => 'Bank SulutGo',
                'swift_code' => null,
                'tipe_bank' => 'BPD',
            ],
            [
                'kode_bank' => '131',
                'nama_bank' => 'PT Bank Pembangunan Daerah Sulawesi Tengah',
                'nama_bank_pendek' => 'Bank Sulteng',
                'swift_code' => null,
                'tipe_bank' => 'BPD',
            ],
            [
                'kode_bank' => '132',
                'nama_bank' => 'PT Bank Pembangunan Daerah Sulawesi Tenggara',
                'nama_bank_pendek' => 'Bank Sultra',
                'swift_code' => null,
                'tipe_bank' => 'BPD',
            ],
            [
                'kode_bank' => '133',
                'nama_bank' => 'PT Bank Pembangunan Daerah Nusa Tenggara Barat',
                'nama_bank_pendek' => 'Bank NTB Syariah',
                'swift_code' => null,
                'tipe_bank' => 'BPD_SYARIAH',
            ],
            [
                'kode_bank' => '134',
                'nama_bank' => 'PT Bank Pembangunan Daerah Bali',
                'nama_bank_pendek' => 'Bank BPD Bali',
                'swift_code' => null,
                'tipe_bank' => 'BPD',
            ],
            [
                'kode_bank' => '135',
                'nama_bank' => 'PT Bank Pembangunan Daerah Nusa Tenggara Timur',
                'nama_bank_pendek' => 'Bank NTT',
                'swift_code' => null,
                'tipe_bank' => 'BPD',
            ],
            [
                'kode_bank' => '136',
                'nama_bank' => 'PT Bank Pembangunan Daerah Maluku dan Maluku Utara',
                'nama_bank_pendek' => 'Bank Maluku Malut',
                'swift_code' => null,
                'tipe_bank' => 'BPD',
            ],
            [
                'kode_bank' => '137',
                'nama_bank' => 'PT Bank Pembangunan Daerah Papua',
                'nama_bank_pendek' => 'Bank Papua',
                'swift_code' => null,
                'tipe_bank' => 'BPD',
            ],

            // ===== TAMBAHAN BANK LAIN YANG MASIH/UMUM DIGUNAKAN DI INDONESIA =====
            [
                'kode_bank' => '4901',
                'nama_bank' => 'PT Super Bank Indonesia',
                'nama_bank_pendek' => 'Superbank',
                'swift_code' => null,
                'tipe_bank' => 'DIGITAL',
            ],
            [
                'kode_bank' => '152',
                'nama_bank' => 'PT Bank Sahabat Sampoerna',
                'nama_bank_pendek' => 'Bank Sampoerna',
                'swift_code' => null,
                'tipe_bank' => 'BUK',
            ],
            [
                'kode_bank' => '517',
                'nama_bank' => 'PT Bank Multiarta Sentosa',
                'nama_bank_pendek' => 'Bank MAS',
                'swift_code' => null,
                'tipe_bank' => 'BUK',
            ],
            [
                'kode_bank' => '950',
                'nama_bank' => 'PT Bank Commonwealth',
                'nama_bank_pendek' => 'Bank Commonwealth',
                'swift_code' => null,
                'tipe_bank' => 'FOREIGN',
                'is_active' => false,
            ],
        ];

        $payload = collect($banks)->map(function ($bank) use ($now) {
            return [
                'kode_bank' => $bank['kode_bank'] ?? null,
                'nama_bank' => $bank['nama_bank'],
                'nama_bank_pendek' => $bank['nama_bank_pendek'] ?? null,
                'swift_code' => $bank['swift_code'] ?? null,
                'tipe_bank' => $bank['tipe_bank'] ?? null,
                'is_active' => $bank['is_active'] ?? true,
                'created_at' => $now,
                'updated_at' => $now,
            ];
        })->values()->all();

        DB::table('master_banks')->upsert(
            $payload,
            ['nama_bank'],
            ['kode_bank', 'nama_bank_pendek', 'swift_code', 'tipe_bank', 'is_active', 'updated_at']
        );
    }
}
